### ISSUE TITLE
Promise no reject when table does not exists - Android

### ISSUE THREAD

**Issue by jlsubia404** [jepiqueau/jeep#7] opened 2020-02-26 02:28 UTC
When you try to get data from a table that doesn't exist, internally occurs an SqlLiteException but this exception does not produce a reject operation on the get promise.

**Comment by jepiqueau** [comment] 2020-02-26 08:12
@jlsubia404 i assume you talk about the capacitor-data-storage-sqlite plugin. A table always exists as when you call openStore or or call setTable with a new table name from an already openStore database, the table is automatically created if not already existing. if you try getting a data with a key which doesn't exist, the return value is null. So i cannot reproduce the issue. Can you be more specific, which plugin capacitor-data-storage-sqlite or capacitor-sqlite. and give me a bit of code so i could reproduce it thanks anyway to use the plugins and report issue. I will do my best to solve it

**Comment by jepiqueau** [comment] 2020-02-26 08:34
@jlsubia404 Ok, i found it it is on capacitor-sqlite so i will have a look

**Comment by jepiqueau** [comment] 2020-02-26 17:59
@jlsubia404 this is fixed in release @jeepq/capacitor@0.0.3
a message has been added in the returned data containing the error message  for all methods
the query method will return an empty area in case of error (table not defined for instance...)
the execute an run commands will return a number of changes equal to -1 in case of error
Voila, for me it could be close when you have test it on your app.

**Closed** 2020-02-27 08:21 UTC
