### ISSUE TITLE
[CapacitorDataStorageSqlite.openStore]: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor

### ISSUE THREAD

**Issue by slevy85** [jepiqueau/jeep#4] opened 2020-02-16 15:19 UTC
Hi, I am migrating form the previous repository to this one, I had no issues before but now I have this exception when I call CapacitorDataStorageSqlite.openStore : 

```
W/SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: select count(*) from sqlite_master;
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:91)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2016)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1902)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2673)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2603)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1247)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1214)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1304)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1292)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1284)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1329)
        at com.jeep.plugins.capacitor.cdssUtils.StorageDatabaseHelper.InitializeSQLCipher(StorageDatabaseHelper.java:100)
        at com.jeep.plugins.capacitor.cdssUtils.StorageDatabaseHelper.<init>(StorageDatabaseHelper.java:86)
        at com.jeep.plugins.capacitor.CapacitorDataStorageSqlite.openStore(CapacitorDataStorageSqlite.java:91)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$2.run(Bridge.java:537)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```
The method call looks like this : 
```
import { Plugins } from '@capacitor/core';
const { CapacitorDataStorageSqlite } = Plugins;

async function set(key, value) {
        await CapacitorDataStorageSqlite.openStore({ database, table });
        return CapacitorDataStorageSqlite.set({ key:`${key}`, value });
}
```

I have installed, synchronyzed and copy the application as usual, and also I have added it to the main activity `add(CapacitorDataStorageSqlite.class);`

Do you have an idea where this comes from ?
Thank you for your help

**Comment by jepiqueau** [comment] 2020-02-17 08:53
@slevy85  Thanks for using the CapacitorDataStorageSqlite plugin. Can you share the project showing the bug on Github, so i can have a look?.  Has  the database was already open in a previous step ? I noticed that you plug the openStore in a function set so i imagine that you should do the same in a function get or others function. This is not required, the openStore is just for creation or opening of the database once, internally the plugin when you call a set is opening the database in read & write mode and when you do a get is opening the database in read-only mode. I suspect this is causing the error as the new version use SQLCipher for encryption which force me to change the initialization plugin process.

**Comment by jepiqueau** [comment] 2020-02-17 10:43
@slevy85 i try but could not replicate the issue even if i include the openStore in each functions like you do
you definitely have to send me your code

**Comment by slevy85** [comment] 2020-02-17 15:26
Unfortunately I don't have a simple project to share, but indeed I use openStore every time because `table` can change, and I remember I had to call openStore everytime to make sure I will read/write the correct table. But that was in the previous plugin, with this one I didn't try yet.

About my environment, if that can help, I don't use ionic, just capacitor with react, can this be problematic ?

**Comment by jepiqueau** [comment] 2020-02-18 08:09
I do not think it is related to the fact that you are using react only.
in your function
```
async function set(key, value) {
        await CapacitorDataStorageSqlite.openStore({ database, table });
        return CapacitorDataStorageSqlite.set({ key:`${key}`, value });
}
```
can you  do 
``` 
async function set(key, value) {
        await CapacitorDataStorageSqlite.openStore({ database, table });
        return await CapacitorDataStorageSqlite.set({ key:`${key}`, value });
}
``` 
and see if it change something. there might be a tentative to read/or write in the same database with not the first action completed.
Now i come back on the fact that you open the store each time you do a set or a get. This is not required.
you openStore once for a database and you  setTable each time you want to change the table in the same database. It is only when you want to store data in another database that you have to use the openStore again with the new database and new table.
As you cannot provide the original code, can you try to replicate on a smaller one and tell me more about the scenario
successive set of data in one database using one table
successive set of data in one database using several tables
successive set of data in multiple database using one table
successive set of data in multiple database using multiple table
in a meantime i will look at a pure react app

**Comment by jepiqueau** [comment] 2020-02-18 19:02
@slevy85  look at https://github.com/jepiqueau/react-datastoragesqlite-app it might help you.
I couldn't reproduce the error

**Comment by slevy85** [comment] 2020-02-19 07:45
Thank you very much for your help, I will take a look and try to fix my code.

**Comment by slevy85** [comment] 2020-02-19 09:07
Also I forgot to precise, my code is working on the browser, but is failing on Android.

Now I did the following :
- open the store once without specifying table
- setTable before every get or set
- await for set to be finished

I don't have the previous exception so it was caused by me using `openStore` too many times, but I have now empty data. I have all keys, but no values in the table.
```
const keys  = await plugin.keys()
console.log('ALL keys are here' + JSON.stringify(keys));
const values = await plugin.values()
console.log("this is null : " + JSON.stringify(values.values[0]));
```

**Comment by jepiqueau** [comment] 2020-02-19 11:17
As i told you the plugin is working fine, try to create a new small application replicating the way you are using the plugin and send me a link to that small application and i could have a look. I am sorry but having 4 lines of code is not enough to understand and advise

**Comment by jepiqueau** [comment] 2020-02-20 09:04
The empty data comes generally to the fact that you may not have call each methods of the plugin with an "await" and so your code is continuing running without waiting for the set or the gt to be completed. May be this can help

**Comment by slevy85** [comment] 2020-02-20 10:45
Thanks god and then thanks to you I found the problem, it was that I was giving the plugin javascript objects while it expects a string using `call.getString`.

I fixed this by using JSON.stringify before setting to the database, and also I parse after the get.
I have to do this only on android because in the browser it was working with objects, so maybe it is something that can be improved ?

**Comment by jepiqueau** [comment] 2020-02-21 08:13
@slevy85  this is clearly said in the line 4 of the DataStorage.md documentation.
```
Capacitor Data Storage SQlite Plugin provides a key-value store for simple data **of type string only**, so **JSON object** can be stored, you should manage conversion through **JSON.stringify** before storing and **JSON.parse** when retrieving the data, use the same procedure for number through number.toString() and Number().
```
and demonstrated in the provided example projects.
You should do it also for Web App in the browser. Thanks to point me out that there is an error here, i will add the check in the web plugin that the input should be of type string .this will be fixed in the next release to avoid the confusion.
Hope now everything is working well for you, so i close the issue

**Closed by jepiqueau** 2020-02-21 08:13 UTC
